{% set name = "dspy-ai" %}
{% set version = "2.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stanfordnlp/dspy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a4e608bea0b666d558a31e17ed3848ef936145aba917a5b1e52bb7632cbbb913

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - pip
  run:
    - python >=3.9,<3.12
    - backoff ~=2.2.1
    - joblib ~=1.3.2
    - openai >=0.28.1,<2.0.0
    - pandas
    - regex
    - ujson
    - tqdm
    - datasets ~=2.14.6,<3.0.0
    - requests
    - optuna
    - pydantic ~=2.0
    - structlog
  run_constrained:
    - anthropic ~=0.18.0
    - chromadb ~=0.4.14
    - fastembed >=0.1.0
    - marqo *
    - qdrant-client >=1.6.2
    - pinecone-client ~=2.2.4
    - weaviate-client ~=4.5.4
    - pymilvus ~=2.3.7
    - boto3 ~=1.34.78

test:
  imports:
    - dspy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stanfordnlp/dspy
  summary: DSPy
  description: |
    DSPy: The framework for programming—not prompting—foundation models
  license: MIT
  license_file: LICENSE
  doc_url: https://dspy-docs.vercel.app/

extra:
  recipe-maintainers:
    - mukhery
