{% set name = "dspy-ai" %}
{% set version = "2.5.39" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stanfordnlp/dspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: eb8491b9884cafcc511fdd89c7d7f3e7c79d85ba48be93f1f2d5b917414aafa3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - backoff ~=2.2
    - joblib ~=1.3
    - openai
    - pandas
    - regex
    - ujson
    - tqdm
    - datasets >=2.14.6,<3.0.0
    - requests
    - optuna
    - pydantic ~=2.0
    - structlog
    - jinja2
    - magicattr
    - diskcache
    - litellm
    - json-repair
    - asyncer
    - anyio
  run_constrained:
    - anthropic >=0.18.0,<1.0.0
    - chromadb ~=0.4.14
    - fastembed >=0.2.0
    - marqo *
    - qdrant-client >=1.11.1
    - pinecone-client ~=2.2.4
    - weaviate-client ~=4.5.4
    - pymilvus ~=2.3.7
    - boto3 ~=1.34.78

test:
  imports:
    - dspy
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/stanfordnlp/dspy
  summary: DSPy
  description: |
    DSPy: The framework for programming—not prompting—foundation models
  license: MIT
  license_file: LICENSE
  doc_url: https://dspy-docs.vercel.app/

extra:
  recipe-maintainers:
    - mukhery
