{% set name = "dspy" %}
{% set version = "2.6.12" %}

package:
  name: dspy-with-alias
  version: {{ version }}

source:
  url: https://github.com/stanfordnlp/dspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 572d41b62552f192699041ae537a1c3d9d738e78960addfe142a3b4e1855b1a3

build:
  number: 0

outputs:
  - name: dspy
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - pip
      run:
        - python >={{ python_min }}
        - backoff
        - joblib ~=1.3
        - openai
        - pandas
        - regex
        - ujson
        - tqdm
        - datasets >=2.14.6
        - requests
        - optuna
        - pydantic ~=2.0
        - structlog
        - jinja2
        - magicattr
        - diskcache
        - litellm
        - json-repair
        - tenacity >=8.2.3
        - anyio
        - asyncer
        - cachetools
        - cloudpickle
      run_constrained:
        - anthropic >=0.18.0,<1.0.0
        - chromadb ~=0.4.14
        - fastembed >=0.2.0
        - marqo *
        - qdrant-client >=1.11.1
        - pinecone-client ~=2.2.4
        - weaviate-client ~=4.5.4
        - pymilvus ~=2.3.7
        - boto3 ~=1.34.78

    test:
      imports:
        - dspy
      requires:
        - python {{ python_min }}

  - name: dspy-ai
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - dspy

about:
  home: https://github.com/stanfordnlp/dspy
  summary: DSPy
  description: |
    DSPy: The framework for programming—not prompting—foundation models
  license: MIT
  license_file: LICENSE
  doc_url: https://dspy-docs.vercel.app/

extra:
  feedstock-name: dspy
  recipe-maintainers:
    - mukhery
